# Generated by Django 2.0.2 on 2018-05-21 09:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20180521_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorialsitepage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short introduction text.', verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='memorialsitepage',
            name='introduction_cs',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short introduction text.', verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='memorialsitepage',
            name='introduction_de',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short introduction text.', verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='memorialsitepage',
            name='description',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(help_text='Eine optionale Überschrift um besonders umfassende Textinhalte weiter zu strukturieren.', label='Optionale Überschrift', required=False)), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), default=[], help_text='Bilder die nahe des eigentlichen Textinhalts des Abschnitts platziert werden sollen.', label='Bilder')), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Der eigentliche Textinhalt des Abschnitts.', label='Inhalt', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('tag', wagtail.core.blocks.CharBlock(help_text='Eine Kennung, welche es erlaubt die Fußnote im Abschnitt in der Form [Kennung] zu referenzieren.', label='Kennung', required=False)), ('footnote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link'], help_text='Zitate, Kommentare und Referenzierungen', label='Fußnote')))), default=[], help_text='Optionale Fußnoten zum Textinhalt.', label='Fußnoten')), ('editor', wagtail.core.blocks.CharBlock(help_text='Der Autor oder Übersetzer, die Autorin oder Übersetzerin des Textinhalts.', label='Editor', required=True))))),), blank=True, help_text='A description of the memorial site and its significance to the referenced authors.', verbose_name='I. Memorial site'),
        ),
        migrations.AlterField(
            model_name='memorialsitepage',
            name='description_cs',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(help_text='Eine optionale Überschrift um besonders umfassende Textinhalte weiter zu strukturieren.', label='Optionale Überschrift', required=False)), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), default=[], help_text='Bilder die nahe des eigentlichen Textinhalts des Abschnitts platziert werden sollen.', label='Bilder')), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Der eigentliche Textinhalt des Abschnitts.', label='Inhalt', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('tag', wagtail.core.blocks.CharBlock(help_text='Eine Kennung, welche es erlaubt die Fußnote im Abschnitt in der Form [Kennung] zu referenzieren.', label='Kennung', required=False)), ('footnote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link'], help_text='Zitate, Kommentare und Referenzierungen', label='Fußnote')))), default=[], help_text='Optionale Fußnoten zum Textinhalt.', label='Fußnoten')), ('editor', wagtail.core.blocks.CharBlock(help_text='Der Autor oder Übersetzer, die Autorin oder Übersetzerin des Textinhalts.', label='Editor', required=True))))),), blank=True, help_text='A description of the memorial site and its significance to the referenced authors.', verbose_name='I. Memorial site'),
        ),
        migrations.AlterField(
            model_name='memorialsitepage',
            name='description_de',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(help_text='Eine optionale Überschrift um besonders umfassende Textinhalte weiter zu strukturieren.', label='Optionale Überschrift', required=False)), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), default=[], help_text='Bilder die nahe des eigentlichen Textinhalts des Abschnitts platziert werden sollen.', label='Bilder')), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Der eigentliche Textinhalt des Abschnitts.', label='Inhalt', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('tag', wagtail.core.blocks.CharBlock(help_text='Eine Kennung, welche es erlaubt die Fußnote im Abschnitt in der Form [Kennung] zu referenzieren.', label='Kennung', required=False)), ('footnote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link'], help_text='Zitate, Kommentare und Referenzierungen', label='Fußnote')))), default=[], help_text='Optionale Fußnoten zum Textinhalt.', label='Fußnoten')), ('editor', wagtail.core.blocks.CharBlock(help_text='Der Autor oder Übersetzer, die Autorin oder Übersetzerin des Textinhalts.', label='Editor', required=True))))),), blank=True, help_text='A description of the memorial site and its significance to the referenced authors.', verbose_name='I. Memorial site'),
        ),
        migrations.AlterField(
            model_name='memorialsitepage',
            name='detailed_description',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(help_text='Eine optionale Überschrift um besonders umfassende Textinhalte weiter zu strukturieren.', label='Optionale Überschrift', required=False)), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), default=[], help_text='Bilder die nahe des eigentlichen Textinhalts des Abschnitts platziert werden sollen.', label='Bilder')), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Der eigentliche Textinhalt des Abschnitts.', label='Inhalt', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('tag', wagtail.core.blocks.CharBlock(help_text='Eine Kennung, welche es erlaubt die Fußnote im Abschnitt in der Form [Kennung] zu referenzieren.', label='Kennung', required=False)), ('footnote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link'], help_text='Zitate, Kommentare und Referenzierungen', label='Fußnote')))), default=[], help_text='Optionale Fußnoten zum Textinhalt.', label='Fußnoten')), ('editor', wagtail.core.blocks.CharBlock(help_text='Der Autor oder Übersetzer, die Autorin oder Übersetzerin des Textinhalts.', label='Editor', required=True))))),), blank=True, help_text='A detailed description of the memorial site and its significance to the referenced authors.', verbose_name='II. Memorial site'),
        ),
        migrations.AlterField(
            model_name='memorialsitepage',
            name='detailed_description_cs',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(help_text='Eine optionale Überschrift um besonders umfassende Textinhalte weiter zu strukturieren.', label='Optionale Überschrift', required=False)), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), default=[], help_text='Bilder die nahe des eigentlichen Textinhalts des Abschnitts platziert werden sollen.', label='Bilder')), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Der eigentliche Textinhalt des Abschnitts.', label='Inhalt', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('tag', wagtail.core.blocks.CharBlock(help_text='Eine Kennung, welche es erlaubt die Fußnote im Abschnitt in der Form [Kennung] zu referenzieren.', label='Kennung', required=False)), ('footnote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link'], help_text='Zitate, Kommentare und Referenzierungen', label='Fußnote')))), default=[], help_text='Optionale Fußnoten zum Textinhalt.', label='Fußnoten')), ('editor', wagtail.core.blocks.CharBlock(help_text='Der Autor oder Übersetzer, die Autorin oder Übersetzerin des Textinhalts.', label='Editor', required=True))))),), blank=True, help_text='A detailed description of the memorial site and its significance to the referenced authors.', verbose_name='II. Memorial site'),
        ),
        migrations.AlterField(
            model_name='memorialsitepage',
            name='detailed_description_de',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(help_text='Eine optionale Überschrift um besonders umfassende Textinhalte weiter zu strukturieren.', label='Optionale Überschrift', required=False)), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), default=[], help_text='Bilder die nahe des eigentlichen Textinhalts des Abschnitts platziert werden sollen.', label='Bilder')), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Der eigentliche Textinhalt des Abschnitts.', label='Inhalt', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('tag', wagtail.core.blocks.CharBlock(help_text='Eine Kennung, welche es erlaubt die Fußnote im Abschnitt in der Form [Kennung] zu referenzieren.', label='Kennung', required=False)), ('footnote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link'], help_text='Zitate, Kommentare und Referenzierungen', label='Fußnote')))), default=[], help_text='Optionale Fußnoten zum Textinhalt.', label='Fußnoten')), ('editor', wagtail.core.blocks.CharBlock(help_text='Der Autor oder Übersetzer, die Autorin oder Übersetzerin des Textinhalts.', label='Editor', required=True))))),), blank=True, help_text='A detailed description of the memorial site and its significance to the referenced authors.', verbose_name='II. Memorial site'),
        ),
    ]
