# Generated by Django 2.0.7 on 2018-07-11 13:22

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20180706_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text='The city or village where the author was born.', max_length=255, verbose_name='Place of birth'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='place_of_birth_cs',
            field=models.CharField(blank=True, help_text='Place of birth if different in Czech spelling.', max_length=255, verbose_name='Place of birth'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='place_of_birth_de',
            field=models.CharField(blank=True, help_text='Place of birth if different in German spelling.', max_length=255, verbose_name='Place of birth'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='place_of_death',
            field=models.CharField(blank=True, help_text='The city or village the author died in.', max_length=255, verbose_name='Place of death'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='place_of_death_cs',
            field=models.CharField(blank=True, help_text='Place of death if different in Czech spelling.', max_length=255, verbose_name='Place of death'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='place_of_death_de',
            field=models.CharField(blank=True, help_text='Place of death if different in German spelling.', max_length=255, verbose_name='Place of death'),
        ),
        migrations.AlterField(
            model_name='agegrouptag',
            name='title_cs',
            field=models.CharField(help_text='The czech title of the tag as show to the user.', max_length=1000, unique=True, verbose_name='Czech title'),
        ),
        migrations.AlterField(
            model_name='agegrouptag',
            name='title_de',
            field=models.CharField(help_text='The german title of the tag as shown to the user.', max_length=1000, unique=True, verbose_name='German title'),
        ),
        migrations.AlterField(
            model_name='authorpage',
            name='genre_tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, db_table='cms_author_tag_genre', help_text='The literary genres the author is associated with.', related_name='authors', to='cms.GenreTag', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='authorpage',
            name='language_tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, db_table='cms_author_tag_language', help_text='The languages that the author has been active in.', related_name='authors', to='cms.LanguageTag', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='authorpage',
            name='literary_period_tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, db_table='cms_author_tag_literary_period', help_text='The literary periods the author has been active in.', related_name='authors', to='cms.LiteraryPeriodTag', verbose_name='Literary periods'),
        ),
        migrations.AlterField(
            model_name='contacttypetag',
            name='title_cs',
            field=models.CharField(help_text='The czech title of the tag as show to the user.', max_length=1000, unique=True, verbose_name='Czech title'),
        ),
        migrations.AlterField(
            model_name='contacttypetag',
            name='title_de',
            field=models.CharField(help_text='The german title of the tag as shown to the user.', max_length=1000, unique=True, verbose_name='German title'),
        ),
        migrations.AlterField(
            model_name='genretag',
            name='title_cs',
            field=models.CharField(help_text='The czech title of the tag as show to the user.', max_length=1000, unique=True, verbose_name='Czech title'),
        ),
        migrations.AlterField(
            model_name='genretag',
            name='title_de',
            field=models.CharField(help_text='The german title of the tag as shown to the user.', max_length=1000, unique=True, verbose_name='German title'),
        ),
        migrations.AlterField(
            model_name='languagetag',
            name='title_cs',
            field=models.CharField(help_text='The czech title of the tag as show to the user.', max_length=1000, unique=True, verbose_name='Czech title'),
        ),
        migrations.AlterField(
            model_name='languagetag',
            name='title_de',
            field=models.CharField(help_text='The german title of the tag as shown to the user.', max_length=1000, unique=True, verbose_name='German title'),
        ),
        migrations.AlterField(
            model_name='literaryperiodtag',
            name='title_cs',
            field=models.CharField(help_text='The czech title of the tag as show to the user.', max_length=1000, unique=True, verbose_name='Czech title'),
        ),
        migrations.AlterField(
            model_name='literaryperiodtag',
            name='title_de',
            field=models.CharField(help_text='The german title of the tag as shown to the user.', max_length=1000, unique=True, verbose_name='German title'),
        ),
    ]
