# Generated by Django 2.0.7 on 2018-08-09 07:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20180711_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this tag as shown to the user.', max_length=1000, unique=True, verbose_name='Title')),
                ('title_de', models.CharField(help_text='The german title of the tag as shown to the user.', max_length=1000, unique=True, verbose_name='German title')),
                ('title_cs', models.CharField(help_text='The czech title of the tag as show to the user.', max_length=1000, unique=True, verbose_name='Czech title')),
                ('description', wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description')),
                ('description_de', wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description')),
                ('description_cs', wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type of location',
                'verbose_name_plural': 'Types of locations',
                'db_table': 'cms_tag_location_type',
            },
        ),
        migrations.AddField(
            model_name='locationpagecontact',
            name='contact_type_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='cms.ContactTypeTag', verbose_name='Contact type'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='location_type_tags',
            field=modelcluster.fields.ParentalManyToManyField(db_table='cms_location_tag_location_type', help_text='The location types that describe this location best.', related_name='locations', to='cms.LocationTypeTag', verbose_name='Location types'),
        ),
    ]
