# Generated by Django 2.0.7 on 2018-08-09 07:11

import uuid

from django.db import migrations, transaction
from django.db.utils import IntegrityError

def init_new_tags(apps, schema_editor):
    """Maps every tag page to a new model tag."""
    LocationTypePage = apps.get_model("cms", "LocationTypePage")
    LocationTypeTag = apps.get_model("cms", "LocationTypeTag")
    for location_type in LocationTypePage.objects.all():
        try:
            with transaction.atomic():
                LocationTypeTag.objects.create(
                    title=location_type.title,
                    title_de=location_type.title_de or uuid.uuid4(),
                    title_cs=location_type.title_cs or uuid.uuid4(),
                )
        except IntegrityError as e:
            print(e)
            pass


def deinit_new_tags(apps, schema_editor):
    LocationTypeTag = apps.get_model("cms", "LocationTypeTag")
    LocationTypeTag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20180809_0711'),
    ]

    operations = [
        migrations.RunPython(init_new_tags, deinit_new_tags)
    ]
