# Generated by Django 2.0.8 on 2018-08-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180815_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmedia',
            name='alt_title',
        ),
        migrations.RemoveField(
            model_name='documentmedia',
            name='alt_title_cs',
        ),
        migrations.RemoveField(
            model_name='documentmedia',
            name='alt_title_de',
        ),
        migrations.RemoveField(
            model_name='documentmedia',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='documentmedia',
            name='caption_cs',
        ),
        migrations.RemoveField(
            model_name='documentmedia',
            name='caption_de',
        ),
        migrations.RemoveField(
            model_name='imagemedia',
            name='alt_title',
        ),
        migrations.RemoveField(
            model_name='imagemedia',
            name='alt_title_cs',
        ),
        migrations.RemoveField(
            model_name='imagemedia',
            name='alt_title_de',
        ),
        migrations.RemoveField(
            model_name='imagemedia',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='imagemedia',
            name='caption_cs',
        ),
        migrations.RemoveField(
            model_name='imagemedia',
            name='caption_de',
        ),
    ]
