# Generated by Django 2.0.8 on 2018-08-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20180815_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmedia',
            name='summary_cs',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Czech summary'),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='summary_de',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='German summary'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='caption_cs',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Czech caption'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='caption_de',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='German caption'),
        ),
    ]
