# Generated by Django 2.0.8 on 2018-08-16 05:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0028_auto_20180816_0523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorsIndex',
            new_name='AuthorIndex',
        ),
        migrations.RenameModel(
            old_name='LocationsPage',
            new_name='LocationIndex',
        ),
    ]
