# Generated by Django 2.0.8 on 2018-08-16 05:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('cms', '0029_auto_20180816_0525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationPage',
            new_name='Location',
        ),
    ]
