# Generated by Django 2.0.8 on 2018-08-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_auto_20180816_0530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactTypeTag',
        ),
    ]
