# Generated by Django 2.0.8 on 2018-08-20 13:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_delete_contacttypetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contact_info',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='An address, a weblink or phone contact that may be helpful to visit this place.', verbose_name='Contact info'),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_info_cs',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='An address, a weblink or phone contact that may be helpful to visit this place.', verbose_name='Contact info'),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_info_de',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='An address, a weblink or phone contact that may be helpful to visit this place.', verbose_name='Contact info'),
        ),
    ]
