# Generated by Django 2.0.8 on 2018-08-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20180828_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i18npage',
            name='alias_for_page',
        ),
        migrations.AddField(
            model_name='i18npage',
            name='temporary_redirect',
            field=models.CharField(blank=True, default='', help_text='A target url or slug that this page will redirect to.', max_length=250, verbose_name='Temporary redirect target'),
        ),
    ]
