# Generated by Django 2.1.7 on 2019-03-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0042_auto_20180914_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmedia',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
    ]
