# Generated by Django 2.1.9 on 2019-06-19 13:50

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_documentmedia_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='remembered_authors',
            field=modelcluster.fields.ParentalManyToManyField(related_name='memorials', to='cms.Author'),
        ),
    ]
