# Generated by Django 2.2.3 on 2019-08-09 11:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_auto_20190808_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level3page',
            name='didactic_material',
            field=wagtail.core.fields.StreamField([('material', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(help_text='A heading that describes the linked document replacing or complementing the files title.', label='Heading', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True)), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'footnote', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='A description of the documents content.', label='Content', required=False)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('tag', wagtail.core.blocks.CharBlock(help_text="A tag that allows to link the footnote with the paragraphs text content in the form '[tag]'.", label='Linkable tag', required=False)), ('footnote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link'], help_text='Citations, comments and references.', label='Footnote'))]), default=[], help_text='Optional footnotes that can be linked in the content description.', label='Footnotes')), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.', label='Editor', required=True))]))], blank=True, help_text='Didactic material that is offered to teachers and students.', verbose_name='Didactic material'),
        ),
        migrations.AlterField(
            model_name='level3page',
            name='didactic_material_cs',
            field=wagtail.core.fields.StreamField([('material', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(help_text='A heading that describes the linked document replacing or complementing the files title.', label='Heading', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True)), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'footnote', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='A description of the documents content.', label='Content', required=False)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('tag', wagtail.core.blocks.CharBlock(help_text="A tag that allows to link the footnote with the paragraphs text content in the form '[tag]'.", label='Linkable tag', required=False)), ('footnote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link'], help_text='Citations, comments and references.', label='Footnote'))]), default=[], help_text='Optional footnotes that can be linked in the content description.', label='Footnotes')), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.', label='Editor', required=True))]))], blank=True, help_text='Didactic material that is offered to teachers and students.', verbose_name='Didactic material'),
        ),
        migrations.AlterField(
            model_name='level3page',
            name='didactic_material_de',
            field=wagtail.core.fields.StreamField([('material', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(help_text='A heading that describes the linked document replacing or complementing the files title.', label='Heading', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True)), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'footnote', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='A description of the documents content.', label='Content', required=False)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('tag', wagtail.core.blocks.CharBlock(help_text="A tag that allows to link the footnote with the paragraphs text content in the form '[tag]'.", label='Linkable tag', required=False)), ('footnote', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link'], help_text='Citations, comments and references.', label='Footnote'))]), default=[], help_text='Optional footnotes that can be linked in the content description.', label='Footnotes')), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.', label='Editor', required=True))]))], blank=True, help_text='Didactic material that is offered to teachers and students.', verbose_name='Didactic material'),
        ),
    ]
