# Generated by Django 2.2.3 on 2019-09-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('cms', '0047_auto_20190809_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='locationauthor',
            name='memorial_site',
        ),
        migrations.RemoveField(
            model_name='memorialsite',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='memorialsite',
            name='title_image',
        ),
        migrations.RemoveField(
            model_name='memorialsiteauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='memorialsiteauthor',
            name='memorial_site',
        ),
        migrations.AddField(
            model_name='documentmedia',
            name='copyright',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='imagemedia',
            name='copyright',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Copyright'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationAuthor',
        ),
        migrations.DeleteModel(
            name='MemorialSite',
        ),
        migrations.DeleteModel(
            name='MemorialSiteAuthor',
        ),
    ]
