# Generated by Django 2.2.5 on 2019-09-10 08:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0048_auto_20190909_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorialPath',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.I18nPage')),
                ('description', wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the highlights of this memorial path.', verbose_name='Description')),
                ('description_de', wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the highlights of this memorial path.', verbose_name='Description')),
                ('description_cs', wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the highlights of this memorial path.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Memorial path',
                'verbose_name_plural': 'Memorial paths',
                'db_table': 'cms_memorial_path',
            },
            bases=('cms.i18npage',),
        ),
        migrations.CreateModel(
            name='MemorialPathIndex',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.I18nPage')),
            ],
            options={
                'verbose_name': 'Memorial paths',
                'db_table': 'cms_memorial_memorial_paths',
            },
            bases=('cms.i18npage',),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='copyright',
            field=models.CharField(blank=True, help_text='License and copyright information regarding this media file.', max_length=2000, null=True, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='copyright',
            field=models.CharField(blank=True, help_text='License and copyright information regarding this media file.', max_length=2000, null=True, verbose_name='Copyright'),
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('memorial', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial_memorial_paths', to='cms.Memorial', verbose_name='Memorial site')),
                ('memorial_path', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='cms.MemorialPath', verbose_name='Memorial path')),
            ],
            options={
                'verbose_name': 'Waypoint',
                'verbose_name_plural': 'Waypoints',
                'db_table': 'cms_memorial_path_waypoint',
            },
        ),
    ]
