# Generated by Django 2.2.8 on 2020-02-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_auto_20191209_1400'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS unaccent;",
            migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "CREATE TEXT SEARCH CONFIGURATION simplesearch ( COPY = simple );",
            "DROP TEXT SEARCH CONFIGURATION simplesearch;"
        ),
        migrations.RunSQL(
            "ALTER TEXT SEARCH CONFIGURATION simplesearch ALTER MAPPING FOR hword, hword_part, word WITH unaccent, german_stem, english_stem, simple;",
            migrations.RunSQL.noop
        )
    ]
