version: '3.5'

services:
  db:
    image: mdillon/postgis:9.6-alpine
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '.5'
          memory: 256M
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lis
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ***PASSWORD***
      PGDATA: /var/lib/postgresql/data/pgdata

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '.5'
          memory: 1G
    networks:
      - lis
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false

  django:
    image: registry.gitlab.com/bentrm/lis:latest
    tty: true
    deploy:
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '1'
          memory: 512M
    networks:
      - lis
      - proxy
    volumes:
      - static:/html/static
      - media:/html/media
    environment:
      VIRTUAL_HOST: ***HOST***
      LETSENCRYPT_HOST: ***HOST***
      LETSENCRYPT_EMAIL: ***EMAIL***
      EMAIL_HOST: ***HOST***
      EMAIL_HOST_USER: ***EMAIL***
      EMAIL_HOST_PASSWORD: ***PASSWORD***
      SECRET_KEY: ***SECRET***
      STATIC_ROOT: /html/static
      STATIC_URL: https://static.lis-map.eu/static/
      MEDIA_ROOT: /html/media
      MEDIA_URL: https://static.lis-map.eu/media/
    depends_on:
      - db
      - elasticsearch

  web:
    image: nginx:alpine
    deploy:
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '.25'
          memory: 256M
    networks:
      - proxy
    volumes:
      - static:/usr/share/nginx/html/static:ro
      - media:/usr/share/nginx/html/media:ro
    environment:
      VIRTUAL_HOST: static.lis-map.eu
      LETSENCRYPT_HOST: static.lis-map.eu
      LETSENCRYPT_EMAIL: ***EMAIL***

volumes:
  pgdata:
  esdata:
  static:
  media:

networks:
  lis:
  proxy:
    external: true
