version: '3.5'

services:
  db:
    image: mdillon/postgis:9.6-alpine
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '.5'
          memory: 128M
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lis
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${LIS_DB_USER}
      POSTGRES_PASSWORD: ${LIS_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    networks:
      - lis
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -server"
      - cluster.name=lis-cluster
      - discovery.type=single-node

  cache:
    image: memcached:alpine
    deploy:
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '.25'
          memory: 256M
    networks:
      - lis

  django:
    image: registry.gitlab.com/bentrm/lis:${LIS_VERSION}
    tty: true
    deploy:
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '1'
          memory: 512M
    networks:
      - lis
      - proxy
    volumes:
      - static:/html/static
      - media:/html/media
    environment:
      CMS_VERSION: ${LIS_VERSION}
      DB_ENGINE: django.contrib.gis.db.backends.postgis
      DB_HOST: db
      DB_NAME: ${LIS_DB_NAME}
      DB_PASSWORD: ${LIS_DB_PASSWORD}
      DB_PORT: ${LIS_DB_PORT}
      DB_USER: ${LIS_DB_USER}
      DEFAULT_FROM_EMAIL: ${LIS_EMAIL_FROM}
      EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
      EMAIL_HOST_PASSWORD: ${LIS_EMAIL_HOST_PASSWORD}
      EMAIL_HOST_USER: ${LIS_EMAIL_HOST_USER}
      EMAIL_HOST: ${LIS_EMAIL_HOST}
      EMAIL_USE_SSL: 0
      EMAIL_USE_TLS: 1
      GOOGLE_MAP_API_KEY: ${LIS_GOOGLE_MAP_API_KEY}
      LETSENCRYPT_EMAIL: ${LIS_LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${LIS_VIRTUAL_HOST}
      MEDIA_ROOT: /html/media
      MEDIA_URL: ${LIS_MEDIA_PATH}/
      SECRET_KEY: ${LIS_SECRET_KEY}
      STATIC_ROOT: /html/static
      STATIC_URL: ${LIS_STATIC_PATH}/
      VIRTUAL_HOST: ${LIS_VIRTUAL_HOST}
      VIRTUAL_PATH: ${LIS_VIRTUAL_PATH}
    depends_on:
      - db
      - elasticsearch

  static:
    image: nginx:alpine
    deploy:
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '.25'
          memory: 64M
    networks:
      - lis
      - proxy
    volumes:
      - static:/usr/share/nginx/html/static:ro
    environment:
      VIRTUAL_HOST: ${LIS_VIRTUAL_HOST}
      VIRTUAL_PATH: ${LIS_STATIC_PATH}

  media:
    image: nginx:alpine
    deploy:
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '.25'
          memory: 64M
    networks:
      - lis
      - proxy
    volumes:
      - media:/usr/share/nginx/html/media:ro
    environment:
      VIRTUAL_HOST: ${LIS_VIRTUAL_HOST}
      VIRTUAL_PATH: ${LIS_MEDIA_PATH}

volumes:
  pgdata:
  esdata:
  static:
  media:

networks:
  lis:
  proxy:
    external: true
