version: '3.7'

services:
  cms:
    build:
      context: ./cms
      args:
        NODE_ENV: development
    restart: "no"
    environment:
      DEBUG: "True"
    volumes:
      - ./cms:/app
      - ./cms/web/dist:/assets/app
