version: '3.7'

services:
  app:
    build:
      context: ./app
      target: builder
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    volumes:
      - ./app/src:/app/src

  cms:
    volumes:
      - ./cms:/app
