version: '3.5'

services:
  db:
    image: mdillon/postgis:10-alpine
    deploy:
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ***PASSWORD***
      PGDATA: /var/lib/postgresql/data/pgdata
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    deploy:
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.allow-origin=http://localhost:1358
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true

  django:
    image: registry.gitlab.com/bentrm/lis:latest
    tty: true
    deploy:
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    ports:
      - 8000:8000
    depends_on:
      - db
      - elasticsearch
    volumes:
      - type: bind
        source: ./src
        target: /src
    command: sh -c "while ! nc -w 1 -z db 5432; do sleep 1; done; /venv/bin/python ./manage.py runserver 0.0.0.0:8000;"

volumes:
  pgdata:
  esdata:
