# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 14:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0043_auto_20180123_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, help_text='The academic title of the author.', max_length=255)),
                ('title_de', models.CharField(blank=True, help_text='The academic title of the author.', max_length=255)),
                ('title_cz', models.CharField(blank=True, help_text='The academic title of the author.', max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('first_name_de', models.CharField(blank=True, max_length=255)),
                ('first_name_cz', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('last_name_de', models.CharField(blank=True, max_length=255)),
                ('last_name_cz', models.CharField(blank=True, max_length=255)),
                ('is_birth_name', models.BooleanField(default=True)),
                ('is_pseudonym', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='I18nPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_de', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, verbose_name='title')),
                ('title_cz', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, verbose_name='title')),
                ('draft_title_de', models.CharField(editable=False, max_length=255)),
                ('draft_title_cz', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AuthorPage',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.I18nPage')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Date of death')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='ContactTypePage',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.I18nPage')),
            ],
            options={
                'verbose_name': 'Contact type',
                'verbose_name_plural': 'Contact types',
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.I18nPage')),
                ('level', models.CharField(choices=[('I', 'I. Discover'), ('II', 'II. Deepen'), ('III', 'III. Research')], max_length=12)),
                ('body', wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.PageChooserBlock(target_model=['home.TextTypePage'])), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'document-link'])), ('quote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('gallery', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock(label='Image')))))),
                ('body_de', wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.PageChooserBlock(target_model=['home.TextTypePage'])), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'document-link'])), ('quote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('gallery', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock(label='Image')))))),
                ('body_cz', wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.PageChooserBlock(target_model=['home.TextTypePage'])), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'document-link'])), ('quote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('gallery', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock(label='Image')))))),
            ],
            options={
                'abstract': False,
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='LiteraryCategoryPage',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.I18nPage')),
            ],
            options={
                'verbose_name': 'Literary category',
                'verbose_name_plural': 'Literary categories',
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='LiteraryPeriodPage',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.I18nPage')),
                ('description', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('description_cz', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('home.i18npage', models.Model),
        ),
        migrations.CreateModel(
            name='MemoryPage',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.I18nPage')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='PoiPage',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.I18nPage')),
                ('description', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('description_cz', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('address_de', models.TextField(blank=True)),
                ('address_cz', models.TextField(blank=True)),
                ('directions', models.TextField()),
                ('directions_de', models.TextField()),
                ('directions_cz', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
            bases=('home.i18npage', models.Model),
        ),
        migrations.CreateModel(
            name='TextTypePage',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.I18nPage')),
            ],
            options={
                'verbose_name': 'Text type',
                'verbose_name_plural': 'Text types',
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='AuthorsPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='ContactTypesPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='LiteraryCategoriesPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='LiteraryPeriodsPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='PoisPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('home.i18npage',),
        ),
        migrations.CreateModel(
            name='TextTypesPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('home.i18npage',),
        ),
        migrations.AddField(
            model_name='authorpagename',
            name='author',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='home.AuthorPage'),
        ),
        migrations.CreateModel(
            name='DeepenContentPage',
            fields=[
            ],
            options={
                'verbose_name': 'II. Deepen',
                'proxy': True,
                'indexes': [],
            },
            bases=('home.contentpage',),
        ),
        migrations.CreateModel(
            name='DiscoverContentPage',
            fields=[
            ],
            options={
                'verbose_name': 'I. Discover',
                'proxy': True,
                'indexes': [],
            },
            bases=('home.contentpage',),
        ),
        migrations.CreateModel(
            name='ResearchContentPage',
            fields=[
            ],
            options={
                'verbose_name': 'III. Research',
                'proxy': True,
                'indexes': [],
            },
            bases=('home.contentpage',),
        ),
    ]
