# Generated by Django 2.0.9 on 2018-10-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_apikey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='name',
        ),
    ]
