# Generated by Django 2.0.8 on 2018-09-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180917_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='requests',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
