# Generated by Django 2.0.8 on 2018-09-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apikey_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='requests',
        ),
    ]
