# Generated by Django 2.0.2 on 2018-04-19 12:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cms.AuthorPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguagePage',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.I18nPage')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'language',
            },
            bases=('cms.i18npage',),
        ),
        migrations.CreateModel(
            name='LanguagesPage',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.I18nPage')),
            ],
            options={
                'verbose_name': 'Languages',
                'db_table': 'languages',
            },
            bases=('cms.i18npage',),
        ),
        migrations.AddField(
            model_name='authorlanguage',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Language that the author has been active in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='cms.LanguagePage', verbose_name='Language'),
        ),
    ]
