# Generated by Django 2.0.2 on 2018-04-17 18:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='locationpagecontact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name (en)'),
        ),
        migrations.AlterField(
            model_name='locationpagecontact',
            name='name_cs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (cs)'),
        ),
        migrations.AlterField(
            model_name='locationpagecontact',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (de)'),
        ),
    ]
