# Generated by Django 2.0.2 on 2018-03-14 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import wagtail.core.models
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('taggit', '0002_auto_20150616_2121'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='documents', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('title_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (de)')),
                ('title_cz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (cz)')),
                ('alt_title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Alternative title')),
                ('alt_title_de', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Alternative title (de)')),
                ('alt_title_cz', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Alternative title (cz)')),
                ('caption', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Media caption')),
                ('caption_de', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Media caption (de)')),
                ('caption_cz', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Media caption (cz)')),
                ('collection', models.ForeignKey(default=wagtail.core.models.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'db_table': 'document',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='imagemedia',
            name='caption',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Media caption'),
        ),
        migrations.AddField(
            model_name='imagemedia',
            name='caption_cz',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Media caption (cz)'),
        ),
        migrations.AddField(
            model_name='imagemedia',
            name='caption_de',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Media caption (de)'),
        ),
    ]
