# Generated by Django 2.0.2 on 2018-03-15 11:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20180314_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepenpage',
            name='body',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote']))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='discoverpage',
            name='body',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote']))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='researchpage',
            name='body',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote']))))),), blank=True),
        ),
    ]
