# Generated by Django 2.0.2 on 2018-03-16 10:42

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20180315_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='i18npage',
            name='editor',
            field=models.CharField(default='Benjamin Thurm', help_text='Name of the author of this content.', max_length=2048, verbose_name='Editor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deepenpage',
            name='body',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(help_text='', required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote'], required=False)), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.'))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='deepenpage',
            name='body_cz',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(help_text='', required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote'], required=False)), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.'))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='deepenpage',
            name='body_de',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(help_text='', required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote'], required=False)), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.'))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='discoverpage',
            name='body',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(help_text='', required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote'], required=False)), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.'))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='discoverpage',
            name='body_cz',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(help_text='', required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote'], required=False)), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.'))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='discoverpage',
            name='body_de',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(help_text='', required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote'], required=False)), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.'))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='researchpage',
            name='body',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(help_text='', required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote'], required=False)), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.'))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='researchpage',
            name='body_cz',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(help_text='', required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote'], required=False)), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.'))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='researchpage',
            name='body_de',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.PageChooserBlock(help_text='', required=True, target_model=['cms.TextTypePage'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'blockquote'], required=False)), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.'))))),), blank=True),
        ),
    ]
