# Generated by Django 2.0.2 on 2018-04-17 19:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180417_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='level2page',
            name='biography',
            field=wagtail.core.fields.StreamField((('Paragraph', wagtail.core.blocks.StructBlock((('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Content of the text block.', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link']), help_text="Citations and comments. The item number can be linked in the content, i.e. '[1]'.")), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.', required=True))))),), blank=True, help_text='An introductory biography of the author aimed at casual users.', verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='level2page',
            name='biography_cs',
            field=wagtail.core.fields.StreamField((('Paragraph', wagtail.core.blocks.StructBlock((('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Content of the text block.', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link']), help_text="Citations and comments. The item number can be linked in the content, i.e. '[1]'.")), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.', required=True))))),), blank=True, help_text='An introductory biography of the author aimed at casual users.', verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='level2page',
            name='biography_de',
            field=wagtail.core.fields.StreamField((('Paragraph', wagtail.core.blocks.StructBlock((('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Content of the text block.', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link']), help_text="Citations and comments. The item number can be linked in the content, i.e. '[1]'.")), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.', required=True))))),), blank=True, help_text='An introductory biography of the author aimed at casual users.', verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='level2page',
            name='works',
            field=wagtail.core.fields.StreamField((('Paragraph', wagtail.core.blocks.StructBlock((('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Content of the text block.', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link']), help_text="Citations and comments. The item number can be linked in the content, i.e. '[1]'.")), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.', required=True))))),), blank=True, help_text='An introduction to the works of the author aimed at casual users.', verbose_name='Works'),
        ),
        migrations.AddField(
            model_name='level2page',
            name='works_cs',
            field=wagtail.core.fields.StreamField((('Paragraph', wagtail.core.blocks.StructBlock((('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Content of the text block.', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link']), help_text="Citations and comments. The item number can be linked in the content, i.e. '[1]'.")), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.', required=True))))),), blank=True, help_text='An introduction to the works of the author aimed at casual users.', verbose_name='Works'),
        ),
        migrations.AddField(
            model_name='level2page',
            name='works_de',
            field=wagtail.core.fields.StreamField((('Paragraph', wagtail.core.blocks.StructBlock((('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'sup', 'ol', 'ul', 'hr', 'link', 'blockquote'], help_text='Content of the text block.', required=True)), ('footnotes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'link']), help_text="Citations and comments. The item number can be linked in the content, i.e. '[1]'.")), ('editor', wagtail.core.blocks.CharBlock(help_text='Author or translator of the content.', required=True))))),), blank=True, help_text='An introduction to the works of the author aimed at casual users.', verbose_name='Works'),
        ),
    ]
