# Generated by Django 2.0.2 on 2018-03-16 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180316_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i18npage',
            name='page_created_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='i18npage',
            name='page_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL, verbose_name='page created by'),
        ),
        migrations.AlterField(
            model_name='i18npage',
            name='page_updated_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='i18npage',
            name='page_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pages', to=settings.AUTH_USER_MODEL, verbose_name='page updated by'),
        ),
    ]
