# Generated by Django 2.0.2 on 2018-03-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20180316_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i18npage',
            name='page_created_at',
        ),
        migrations.RemoveField(
            model_name='i18npage',
            name='page_created_by',
        ),
        migrations.RemoveField(
            model_name='i18npage',
            name='page_updated_at',
        ),
        migrations.RemoveField(
            model_name='i18npage',
            name='page_updated_by',
        ),
    ]
