# Generated by Django 2.0.2 on 2018-03-26 10:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20180326_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorialSiteAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorial_sites', to='cms.AuthorPage')),
                ('memorial_site', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='cms.MemorialSitePage')),
            ],
            options={
                'db_table': 'memorial_site_author',
            },
        ),
    ]
