# Generated by Django 2.0.2 on 2018-03-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_memorialsiteauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorialsitepage',
            name='author',
        ),
    ]
