# Generated by Django 2.0.2 on 2018-03-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_remove_memorialsitepage_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorpagename',
            old_name='birth_name_cz',
            new_name='birth_name_cs',
        ),
        migrations.RenameField(
            model_name='authorpagename',
            old_name='first_name_cz',
            new_name='first_name_cs',
        ),
        migrations.RenameField(
            model_name='authorpagename',
            old_name='last_name_cz',
            new_name='last_name_cs',
        ),
        migrations.RenameField(
            model_name='authorpagename',
            old_name='title_cz',
            new_name='title_cs',
        ),
        migrations.RenameField(
            model_name='deepenpage',
            old_name='body_cz',
            new_name='body_cs',
        ),
        migrations.RenameField(
            model_name='discoverpage',
            old_name='body_cz',
            new_name='body_cs',
        ),
        migrations.RenameField(
            model_name='documentmedia',
            old_name='alt_title_cz',
            new_name='alt_title_cs',
        ),
        migrations.RenameField(
            model_name='documentmedia',
            old_name='caption_cz',
            new_name='caption_cs',
        ),
        migrations.RenameField(
            model_name='documentmedia',
            old_name='title_cz',
            new_name='title_cs',
        ),
        migrations.RenameField(
            model_name='i18npage',
            old_name='draft_title_cz',
            new_name='draft_title_cs',
        ),
        migrations.RenameField(
            model_name='i18npage',
            old_name='title_cz',
            new_name='title_cs',
        ),
        migrations.RenameField(
            model_name='imagemedia',
            old_name='alt_title_cz',
            new_name='alt_title_cs',
        ),
        migrations.RenameField(
            model_name='imagemedia',
            old_name='caption_cz',
            new_name='caption_cs',
        ),
        migrations.RenameField(
            model_name='imagemedia',
            old_name='title_cz',
            new_name='title_cs',
        ),
        migrations.RenameField(
            model_name='literaryperiodpage',
            old_name='description_cz',
            new_name='description_cs',
        ),
        migrations.RenameField(
            model_name='locationpage',
            old_name='address_cz',
            new_name='address_cs',
        ),
        migrations.RenameField(
            model_name='locationpage',
            old_name='description_cz',
            new_name='description_cs',
        ),
        migrations.RenameField(
            model_name='locationpage',
            old_name='directions_cz',
            new_name='directions_cs',
        ),
        migrations.RenameField(
            model_name='researchpage',
            old_name='body_cz',
            new_name='body_cs',
        ),
    ]
