# Generated by Django 2.0.2 on 2018-04-08 19:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20180328_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorialsitepage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='memorialsitepage',
            name='description_cs',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='memorialsitepage',
            name='description_de',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
