# Generated by Django 2.0.2 on 2018-04-09 06:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20180408_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level1Page',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.I18nPage')),
                ('biography', wagtail.core.fields.RichTextField(blank=True)),
                ('biography_de', wagtail.core.fields.RichTextField(blank=True)),
                ('biography_cs', wagtail.core.fields.RichTextField(blank=True)),
                ('works', wagtail.core.fields.RichTextField(blank=True)),
                ('works_de', wagtail.core.fields.RichTextField(blank=True)),
                ('works_cs', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'db_table': 'level_1',
            },
            bases=('cms.i18npage',),
        ),
    ]
