# Generated by Django 2.0.2 on 2018-06-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20180621_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorlanguage',
            options={},
        ),
        migrations.AlterModelTable(
            name='authorlanguage',
            table='author_language',
        ),
    ]
