# Generated by Django 2.0.2 on 2018-04-09 06:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_level1page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level2Page',
            fields=[
                ('level1page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.Level1Page')),
                ('perception', wagtail.core.fields.RichTextField(blank=True)),
                ('perception_de', wagtail.core.fields.RichTextField(blank=True)),
                ('perception_cs', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'db_table': 'level_2',
            },
            bases=('cms.level1page',),
        ),
    ]
