# Generated by Django 2.0.2 on 2018-04-09 06:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_level2page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level3Page',
            fields=[
                ('i18npage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.I18nPage')),
                ('primary_literature', wagtail.core.fields.RichTextField(blank=True)),
                ('primary_literature_de', wagtail.core.fields.RichTextField(blank=True)),
                ('primary_literature_cs', wagtail.core.fields.RichTextField(blank=True)),
                ('testimony', wagtail.core.fields.RichTextField(blank=True)),
                ('testimony_de', wagtail.core.fields.RichTextField(blank=True)),
                ('testimony_cs', wagtail.core.fields.RichTextField(blank=True)),
                ('secondary_literature', wagtail.core.fields.RichTextField(blank=True)),
                ('secondary_literature_de', wagtail.core.fields.RichTextField(blank=True)),
                ('secondary_literature_cs', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'db_table': 'level_3',
            },
            bases=('cms.i18npage',),
        ),
    ]
