# Generated by Django 2.0.2 on 2018-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20180703_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this tag as shown to the user.', max_length=1000, verbose_name='Title')),
                ('title_de', models.CharField(blank=True, help_text='The german title of the tag as shown to the user.', max_length=1000, verbose_name='German title')),
                ('title_cs', models.CharField(blank=True, help_text='The czech title of the tag as show to the user.', max_length=1000, verbose_name='Czech title')),
                ('sort_order', models.IntegerField(help_text='Defines the relative order of the group in the UI.', verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Age group',
                'verbose_name_plural': 'Age groups',
                'db_table': 'cms_tag_age_group',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this tag as shown to the user.', max_length=1000, verbose_name='Title')),
                ('title_de', models.CharField(blank=True, help_text='The german title of the tag as shown to the user.', max_length=1000, verbose_name='German title')),
                ('title_cs', models.CharField(blank=True, help_text='The czech title of the tag as show to the user.', max_length=1000, verbose_name='Czech title')),
            ],
            options={
                'verbose_name': 'Contact type',
                'verbose_name_plural': 'Contact types',
                'db_table': 'cms_tag_contact_type',
            },
        ),
        migrations.CreateModel(
            name='LiteraryPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this tag as shown to the user.', max_length=1000, verbose_name='Title')),
                ('title_de', models.CharField(blank=True, help_text='The german title of the tag as shown to the user.', max_length=1000, verbose_name='German title')),
                ('title_cs', models.CharField(blank=True, help_text='The czech title of the tag as show to the user.', max_length=1000, verbose_name='Czech title')),
                ('sort_order', models.IntegerField(help_text='Defines the relative order of the period in the UI.', verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Literary period',
                'verbose_name_plural': 'Literary periods',
                'db_table': 'cms_tag_period',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='authorlanguage',
            options={'verbose_name': 'Language of the author', 'verbose_name_plural': 'Languages of the author'},
        ),
    ]
