# Generated by Django 2.0.2 on 2018-04-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('cms', '0014_level3page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepenpage',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='discoverpage',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='researchpage',
            name='i18npage_ptr',
        ),
        migrations.AlterModelOptions(
            name='level1page',
            options={'verbose_name': 'I. Discover page'},
        ),
        migrations.AlterModelOptions(
            name='level2page',
            options={'verbose_name': 'II. Deepen page'},
        ),
        migrations.AlterModelOptions(
            name='level3page',
            options={'verbose_name': 'III. Research page'},
        ),
        migrations.DeleteModel(
            name='DeepenPage',
        ),
        migrations.DeleteModel(
            name='DiscoverPage',
        ),
        migrations.DeleteModel(
            name='ResearchPage',
        ),
    ]
