# Generated by Django 2.0.2 on 2018-07-03 13:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20180703_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='description_cs',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='description_de',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='description_cs',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='description_de',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_cs',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_de',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='language',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='language',
            name='description_cs',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='language',
            name='description_de',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='literaryperiod',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='literaryperiod',
            name='description_cs',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='literaryperiod',
            name='description_de',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the tag.', verbose_name='Description'),
        ),
    ]
