# Generated by Django 2.0.2 on 2018-07-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20180703_1347'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='literaryperiod',
            table='cms_tag_literary_period',
        ),
    ]
