# Generated by Django 2.0.8 on 2018-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20180815_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmedia',
            name='summary',
            field=models.CharField(null=True, blank=True, help_text='A short and concise summary of the content of the document.', max_length=2000, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='documentmedia',
            name='summary_cs',
            field=models.CharField(null=True, blank=True, help_text='A short and concise summary of the content of the document.', max_length=2000, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='documentmedia',
            name='summary_de',
            field=models.CharField(null=True, blank=True, help_text='A short and concise summary of the content of the document.', max_length=2000, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='imagemedia',
            name='new_caption',
            field=models.CharField(null=True, blank=True, help_text='A caption that may be presented with the file.', max_length=1024, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='imagemedia',
            name='new_caption_cs',
            field=models.CharField(null=True, blank=True, help_text='Caption in Czech translations.', max_length=1024, verbose_name='Czech caption'),
        ),
        migrations.AddField(
            model_name='imagemedia',
            name='new_caption_de',
            field=models.CharField(null=True, blank=True, help_text='Caption in German translations.', max_length=1024, verbose_name='German caption'),
        ),
    ]
