# Generated by Django 2.0.8 on 2018-08-15 09:33

from django.db import migrations
from django.db.utils import IntegrityError

def migrate_media_attributes(apps, schema_editor):
    ImageMedia = apps.get_model("cms", "ImageMedia")
    for image in ImageMedia.objects.order_by("title"):
        image.new_caption = image.caption
        image.new_caption_de = image.caption_de
        image.new_caption_cs = image.caption_cs
        if image.alt_title and not image.new_caption:
            image.new_caption = image.alt_title
        if image.alt_title_de and not image.new_caption_de:
            image.new_caption_de = image.alt_title_de
        if image.alt_title_cs and not image.new_caption_cs:
            image.new_caption_cs = image.alt_title_cs
        image.save()

    DocumentMedia = apps.get_model("cms", "DocumentMedia")
    for document in DocumentMedia.objects.order_by("title"):
        if document.alt_title and not document.summary:
            document.summary = document.alt_title
        if document.alt_title_de and not document.summary_de:
            document.summary_de = document.alt_title_de
        if document.alt_title_cs and not document.summary_cs:
            document.summary_cs = document.alt_title_cs
        document.save()

def revert_migration(apps, schema_editor):
    ImageMedia = apps.get_model("cms", "ImageMedia")
    for image in ImageMedia.objects.order_by("title"):
        image.new_caption = ""
        image.new_caption_de = ""
        image.new_caption_cs = ""
        image.save()

    DocumentMedia = apps.get("cms", "DocumentMedia")
    for document in DocumentMedia.objects.order_by("title"):
        document.summary = ""
        document.summary_de = ""
        document.summary_cs = ""
        document.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20180815_1048'),
    ]

    operations = [
        migrations.RunPython(migrate_media_attributes, revert_migration)
    ]
