# Generated by Django 2.0.8 on 2018-08-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('cms', '0025_auto_20180815_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorlanguage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorlanguage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='authorliterarycategory',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorliterarycategory',
            name='literary_category',
        ),
        migrations.RemoveField(
            model_name='authorliteraryperiod',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorliteraryperiod',
            name='literary_period',
        ),
        migrations.RemoveField(
            model_name='contacttypepage',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='contacttypespage',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='languagepage',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='languagespage',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='literarycategoriespage',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='literarycategorypage',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='literaryperiodpage',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='literaryperiodspage',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='locationpagecontact',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='locationpagecontact',
            name='contact_type_tag',
        ),
        migrations.RemoveField(
            model_name='locationpagecontact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='locationtypepage',
            name='i18npage_ptr',
        ),
        migrations.RemoveField(
            model_name='locationtypespage',
            name='i18npage_ptr',
        ),
        migrations.AlterModelOptions(
            name='contentindexpage',
            options={'verbose_name': 'Content'},
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='location_type',
        ),
        migrations.DeleteModel(
            name='AuthorLanguage',
        ),
        migrations.DeleteModel(
            name='AuthorLiteraryCategory',
        ),
        migrations.DeleteModel(
            name='AuthorLiteraryPeriod',
        ),
        migrations.DeleteModel(
            name='ContactTypePage',
        ),
        migrations.DeleteModel(
            name='ContactTypesPage',
        ),
        migrations.DeleteModel(
            name='LanguagePage',
        ),
        migrations.DeleteModel(
            name='LanguagesPage',
        ),
        migrations.DeleteModel(
            name='LiteraryCategoriesPage',
        ),
        migrations.DeleteModel(
            name='LiteraryCategoryPage',
        ),
        migrations.DeleteModel(
            name='LiteraryPeriodPage',
        ),
        migrations.DeleteModel(
            name='LiteraryPeriodsPage',
        ),
        migrations.DeleteModel(
            name='LocationPageContact',
        ),
        migrations.DeleteModel(
            name='LocationTypePage',
        ),
        migrations.DeleteModel(
            name='LocationTypesPage',
        ),
    ]
