# Generated by Django 2.0.8 on 2018-08-16 05:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('cms', '0026_auto_20180816_0505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorsPage',
            new_name='AuthorsIndex',
        ),
    ]
