# Generated by Django 2.0.8 on 2018-08-16 05:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('cms', '0030_auto_20180816_0526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemorialSitePage',
            new_name='MemorialSite',
        ),
    ]
