# Generated by Django 2.0.8 on 2018-09-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_auto_20180828_0926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationTypeTag',
            new_name='MemorialTag',
        ),
        migrations.AlterModelOptions(
            name='memorialtag',
            options={'verbose_name': 'Type of memorials', 'verbose_name_plural': 'Types of memorials'},
        ),
        migrations.AlterModelTable(
            name='memorialtag',
            table='cms_tag_memorial_type',
        ),
    ]
