# Generated by Django 2.0.8 on 2018-09-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_auto_20180913_1039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiteraryPeriodTag',
            new_name='PeriodTag',
        ),
    ]
